/**
 * For handling errors generated by our app
 * @see ErrorTypes
 * @class
 */
class AppError extends Error {
    constructor({ message, code }) {
        super(message);
        this.code = code;
    }
}
/** For errors related to development such as missing config or incorrect function usage */
class DevelopmentError extends AppError {}

/** Errors related to missing authorization of user */
class AuthorizationError extends AppError {}

/** Errors related to missing or incorrect API parameters */
class ValidationError extends AppError {}

/** For errors coming from broker APIs, such as rate limit or authorization errors */
class BrokerError extends AppError {}

module.exports = {
    AppError,
    AuthorizationError,
    ValidationError,
    DevelopmentError,
    BrokerError,
}